### ISSUE TITLE
work up physiological limits

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#1]
@alanaroseo What are the physiological limits? Thermal limits ... Turgor limits? Cell expansion limits? 

Remember IAACKandGAinwoodformation2022Aloni and Zweifel_etal_2021

@lizzieinvancouver will send Parent et al. 2012 and other Wang & Engel stuff

**Comment by lizzieinvancouver** [comment]
@alanaroseo I feel like you have probably done this and we could close this soon? Did the Parent et al. 2012 and other Wang & Engel articles I sent match up in terms of what temperatures are too high etc.? I think the curve difference in shape must be due to growth (your shape) versus development (WE shape). Also see [this semi interesting article](https://www.sciencedirect.com/science/article/pii/S2212094715300116)....

Anyway, I suggest you jot down some quick replies and close this issue!

**Comment by alanaroseo** [comment]
Hi, yes, I think the difference in curve shape is devo vs growth, overall the temperatures are pretty similar. Zweifel et al. is more about turgor limited growth, in that it depends also on temperature because of the link between turgor and VPD. This fits also with Peters et al: 
(Peters, R.L., Steppe, K., Cuny, H.E., De Pauw, D.J., Frank, D.C., Schaub, M., Rathgeber, C.B., Cabon, A. and Fonti, P., 2021. Turgor–a limiting factor for radial growth in mature conifers along an elevational gradient. New Phytologist, 229(1), pp.213-229.)

The process of turgor limiting growth is well known, these are good mechanistic sources:

        Cosgrove, D.J., 1987. Wall relaxation and the driving forces for cell expansive growth. Plant physiology, 84(3), pp.561-564.

        Cosgrove, D.J., Van Volkenburgh, E. and Cleland, R.E., 1984. Stress relaxation of cell walls and the yield threshold for growth. Planta, 162(1), pp.46-54.

I have a long list of drought and growth citations we can fill in.

As for temperature:

There is a mismatch between thermal range of photosynthesis and that of growth, I think the Cabon paper is good and also recent
Cabon, A., Kannenberg, S.A., Arain, A., Babst, F., Baldocchi, D., Belmecheri, S., Delpierre, N., Guerrieri, R., Maxwell, J.T., McKenzie, S. and Meinzer, F.C., 2022. Cross-biome synthesis of source versus sink limits to tree growth. Science, 376(6594), pp.758-761.

Although warm springs activate cambial growth sooner, the temp threshold for growth is very species specific:
Begum, S., Kudo, K., Rahman, M.H., Nakaba, S., Yamagishi, Y., Nabeshima, E., Nugroho, W.D., Oribe, Y., Kitin, P., Jin, H.O. and Funada, R., 2018. Climate change and the regulation of wood formation in trees by temperature. Trees, 32, pp.3-15.

It can be warm enough for photosynthesis, but too cold for cambial division in boreal forests:
Rossi, S., Deslauriers, A., Griçar, J., Seo, J.W., Rathgeber, C.B., Anfodillo, T., Morin, H., Levanic, T., Oven, P. and Jalkanen, R., 2008. Critical temperatures for xylogenesis in conifers of cold climates. Global Ecology and Biogeography, 17(6), pp.696-707.

Temperature increases are more likely to increase growth in angiosperm trees than conifers, and mostly reduce growth in the tropics
Way & Oren 2010. Differential responses to changes in growth temperature between trees from different functional groups and biomes: a review and synthesis of data
from Way & Oren:
![image](https://github.com/lizzieinvancouver/grephon/assets/35076544/2771a210-04e5-41f5-863a-800d26997aab)

Hot summers increase growth at high elevation and suppress it at low elevation:
Jolly, W.M., Dobbertin, M., Zimmermann, N.E. and Reichstein, M., 2005. Divergent vegetation growth responses to the 2003 heat wave in the Swiss Alps. Geophysical Research Letters, 32(18).
Martinez-Meier, A., Sanchez, L., Pastorino, M., Gallo, L. and Rozenberg, P., 2008. What is hot in tree rings? The wood density of surviving Douglas-firs to the 2003 drought and heat wave. Forest Ecology and Management, 256(4), pp.837-843.

A basic overview of thermal tolerance across plants is Wahid et al. . The synopsis is that the induction of heat shock proteins, ROS, membrane instability, and exceeding the thermal optimum for photosynthesis (too much photorespiration and eventually photosystem damage) reduces growth. 
Wahid, A., Gelani, S., Ashraf, M., & Foolad, M. R. (2007). Heat tolerance in plants: An overview. Environmental and Experimental Botany, 61(3), 199-223. -

General take home is that this is biome, clade. and species specific. We know much more about how cold limits growth than how heat does because the thresholds are more generalizable for cold and the interaction with water availability is hard to tease apart for heat.

**Comment by lizzieinvancouver** [comment]
@FrederikBaumgarten Just flagging this issue for you, as it has GREAT info!

**Comment by lizzieinvancouver** [comment]
@alanaroseo Hello! I am re-opening this issue based on some ms comments I got, semi-related to this figure: 

![grephonfig](https://github.com/lizzieinvancouver/grephon/assets/2153556/ea60ae90-872e-4729-ace2-ba3145c0f973)

I was wondering if you have any references on the shape of the GROWTH response to temperature curve? Could be number of cells added, shoot elongation etc. [Parent et al. 2012](https://github.com/lizzieinvancouver/grephon/blob/main/articles/Parent_etal_2012.pdf) has some of these and they're always non-linear. I have been looking around too and finding some theory papers arguing for Gaussian (e.g., [this Amarasekare paper makes an argument for Gaussian for reproductive stuff](https://www.journals.uchicago.edu/doi/full/10.1086/690293), or [here's a recent PNAS theory paper too](https://www.biorxiv.org/content/10.1101/2021.04.26.441387v2.full.pdf) ... of course it's WAY nicer to assume this for a model) but not much else. I don't know of any empirical data showing symmetrical growth rate x temperature curves, do you?

If not, I think we probably need to expand the figure some and take on this issue head-on.....

**Comment by alanaroseo** [comment]
Hmmm, no I don't know any from the last 40 or so years for growth, just photosynthesis. Really, I drew it too symmetric - should probably update. It's symmetrical-ish, but with a sudden drop which was meant to be the red dashed line in the figure, but I should have just chopped it off

anyhow, it's  like this one from 
Hikosaka, K., Ishikawa, K., Borjigidai, A., Muller, O. and Onoda, Y., 2006. Temperature acclimation of photosynthesis: mechanisms involved in the changes in temperature dependence of photosynthetic rate. Journal of experimental botany, 57(2), pp.291-302.

![m_jexboterj049f04_lw](https://github.com/lizzieinvancouver/grephon/assets/35076544/bf282961-fbb3-4975-bbf3-d65e6331f403)

If we want to reach way back, Abrami and others in the 1970s described the growth/temp curve as logistic, which does seem logical, putting growth rate (y' of growth) as a gaussian-type shape

Abrami, G., 1972. Optimum mean temperature for a plant growth calculated by a new method of summation. Ecology, 53(5), pp.893-900.

**Comment by alanaroseo** [comment]
It might be better to draw the dashed line/drop-off as a zone since between 32-40 we see species-specific differences. The problem is that photosynthesis can go to about 40, but growth seems to stop sooner

The classic example paper is Smertenko et al. 1997 that saw a hard limit to cell division at 38 C, but that's in tobacco which is super heat tolerant and can photosynthesize until at least 40C

Smertenko, A., DRÁBER, P., Viklický, V. and Opatrný, Z., 1997. Heat stress affects the organization of microtubules and cell division in Nicotiana tabacum cells. Plant, Cell & Environment, 20(12), pp.1534-1542.

On the whole though, I think the evidence that photosynthesis continues under conditions where water stress is too much for growth is way more clear than photosynthesis continuing when it is too hot for growth. I think maybe we should focus on heat as something that increases the water-stress related photosynthesis/growth gap rather than a stand alone.

Here's some papers saying that plants continue to photosynthesize when too droughted to grow:

Palacio, S., Hoch, G., Sala, A., Körner, C. and Millard, P., 2013. Does carbon storage limit tree growth?. New Phytologist, 201: 1096–1100.

Boyer JS. 1970. Leaf enlargement and metabolic rates in corn, soybean, and sunflower at various leaf water potentials. Plant Physiology, 46: 233–235.

Hsiao TC, Acevedo E. 1974. Plant responses to water deficits, water-use efficiency, and drought resistance. Agricultural Meteorology, 14: 59–84.

Dosio GAA, Tardieu F, Turc O. 2011. Floret initiation, tissue expansion and carbon availability at the meristem of the sunflower capitulum as affected by water or light deficits. New Phytologist, 189: 94–105.

Muller B, Pantin F,G_enardM,Turc O, Freixes S, PiquesM,Gibon Y. 2011. Water deficits uncouple growth from photosynthesis, increase C content, and modify the relationships between C and growth in sink organs. Journal of Experimental Botany, 62: 1715–1729.

**Comment by lizzieinvancouver** [comment]
@alanaroseo Thanks for this! Interesting to see the Hikosaka et al. 2006 paper, which seems to show a bunch of curves depending on the exact process which is interesting -- I will say that non-symmetrical curve for 'Rubisco regeneration-limited photosynthesis and leaf temperature' does not look like a good fit. But the shape is similar to Parent, so it looks like a best guess for growth is assymetrical. 

> It might be better to draw the dashed line/drop-off as a zone since between 32-40 we see species-specific differences. The problem is that photosynthesis can go to about 40, but growth seems to stop sooner
> 
> The classic example paper is Smertenko et al. 1997 that saw a hard limit to cell division at 38 C, but that's in tobacco which is super heat tolerant and can photosynthesize until at least 40C

I think one point -- or a couple -- we could make here is that:

1. We don't know this response f(x) well for trees, that's a problem. Like Smertenko, Parent et al. is all crops.
2. The insect people have done more work interrogating what the best curve is ... I found a lot of insect papers from cited Abrami. Like `[Modeling Insect Development Rates: a Literature Review and Application of a Biophysical Model](https://academic.oup.com/aesa/article-abstract/77/2/208/164625?redirectedFrom=PDF&login=true#no-access-message#no-access-message)' and when I ask about 'what curve?' from plant colleagues who work on this, they send me insect papers.

> If we want to reach way back, Abrami and others in the 1970s described the growth/temp curve as logistic, which does seem logical, putting growth rate (y' of growth) as a gaussian-type shape

I only skimmed this paper, but Abrami argues for summation (like GDD), and summation processes are logistic, basically. We could even cite [me](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.15746) for that! Or there are older papers, I can track down.

**Comment by alanaroseo** [comment]
Ooooo @lizzieinvancouver your paper is really cool!

I think the reason insect biologists do this better is because insects do it better, they don't have to rely on rubisco for energy intake. Because oxidation rates increase way faster than carboxilation rates the efficiency of photosynthetic energy capture drops as reaction rates increase. So leaf out should be a thermal-additive process (until the enzymes fall apart) because it uses stored energy, but plant growth might not be, because it uses acquired energy. And yes, we only know the slightest thing about growth in crops and pretty much nothing about trees. A bit of almond and pistachio yield data with temp, but not their growth.  

We need to somehow convey how freakin complicated it all is...

**Comment by lizzieinvancouver** [comment]
@alanaroseo Cool point about insects! Maybe I should move away from plants .....

> bit of almond and pistachio yield

Sounds delicious!

Anyway, one more query! Do you know of ANY experiments that teased out temperature versus growing season length? I have a spot in the ms to point to this fundamental thing in physiology ... but no studies. (In chatting with @AileneKane today we looked at a bunch but they are all correlational so when they say they teased out temperature affecting rates versus longer seasons, I say 'yeah, right, you totally did not.')

**Comment by alanaroseo** [comment]
Hmmm, no I don’t know of any papers with a well-designed experiment to
tease out temp and season length. Lots of correlations, but few tests. Plus
most physiology has sketchy stats (looking at you L. Sack) so it can be
hard to read the meaning.

More reason to advocate for coordination between phys and pheno camps….

**Comment by lizzieinvancouver** [comment]
@alanaroseo @AileneKane @FrederikBaumgarten @kavs-P 
Hi all, I am struggling to write up what is a source versus sink limitation. If source meant not enough CO2 for photosynthesis, I think I would be fine, but source seems to mean 'not enough photosynthesis' including due to high temperatures. But I think high temperatures should be a sink limitation, as the plant cannot photosynthesize. If this is the definition, then internal constraints such as genetic etc. constraints can fall under both source and sink limitation (different species have different thermal limits for photosynthesis). Can anyone clarify for me? I will stick with what is the definition in our figure for now.

**Comment by lizzieinvancouver** [comment]
@alanaroseo @AileneKane @kavs-P @FrederikBaumgarten

In case it helps, here's the text I am struggling to write:

> Studies from the disciplines of dendrochronology (the study of tree rings and their dating) and physiology have readily offered mechanisms for the recent results that increased growth may not come with longer seasons. Hypotheses focus on both source (photosynthesis-limited, including $CO_2$ limitation) and sink limitations (Fig. \ref{fig:temperaturecomplex}). External climatic drivers that offset the positive growth effects of longer seasons are often reported in tree ring studies suggested when higher temperatures and lower precipitation produce negative correlations with growth (source??). In contrast, several other studies suggested fundamental developmental constraints that prevent trees from responding to longer seasons (sink limitation).

**Comment by lizzieinvancouver** [comment]
@alanaroseo 
While I am typing away, perhaps we could add to this figure something (like an arrow or dot on the curve that we mention in the caption or something) that goes with this text (if we keep it in the paper, so we ca wait and see):

> At very cool temperatures, a small increase in warming may have limited effect, whereas warming that pushes plant beyond their optima, where many rates crash, could have large impacts. In between, warming would linearly increase rates.

**Comment by lizzieinvancouver** [comment]
@alanaroseo Best definition: Anything limiting assimilation is source (photosynthesis but not sequestered); anything limiting accumulation is sink (photosynthesis and we know where it's going, as in growth or sequestration).

**Comment by alanaroseo** [comment]
Just realized I never hit send on the reply below:

I can add that later. I would say: at very cold temperatures many
growth-related processes are rate-limited, beyond the minimal temperature
threshold for growth, a small increase in temperature has a large impact on
growth

**Comment by lizzieinvancouver** [comment]
See also.... https://github.com/lizzieinvancouver/grephon/tree/main/notes/tempresponsecurves

![Graph](https://github.com/lizzieinvancouver/grephon/assets/2153556/365b6966-a21a-4a41-a214-91f99dd4731a)
