### ISSUE TITLE
agree on minimum set of growth metrics

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#15]
I need help going from this list:
```
> unique(d$growth)
 [1] "annual core"                            "intra-annual core (xylogeneis)"        
 [3] "growth anomalies"                       "annual core (simulated to intraannual)"
 [5] "ecosystem fluxes"                       "photosynthesis"                        
 [7] "dendrometer/circumference"              "height"                                
 [9] "NDVI/greenness"                         "biomass"                               
[11] "root:shoot ratio"                       "cell production (number of cells)"     
[13] "not measured"                           "stem density"   
```

To ideally 3-5 metrics (for example, for the figures). I think we must have:

1. not measured
2. annual core
3. intra-annual core

Others could be ... 
4. ecosystem fluxes
5. dendrometer/circumference
6. ... ?

Here's how many of each we have:
```
> table((d$growth))

                           annual core annual core (simulated to intraannual) 
                                    13                                      1 
                               biomass      cell production (number of cells) 
                                     2                                      1 
             dendrometer/circumference                       ecosystem fluxes 
                                     7                                     13 
                      growth anomalies                                 height 
                                     1                                      6 
        intra-annual core (xylogeneis)                         NDVI/greenness 
                                     6                                      2 
                          not measured                         photosynthesis 
                                     1                                      7 
                      root:shoot ratio                           stem density 
                                     1                                      1 
```

I think for phenology we can slim easily to:

1. vegetative
2. wood
3. climate + date
4. not measured

But let me know if you do not like this plan.

**Comment by alanaroseo** [comment]
Are we sure stem density was a growth metric?

For growth metric how about:
                                                

1. Adult trunk radial growth: ( "annual core"  , "intra-annual core (xylogeneis)"   ,  "annual core (simulated to intraannual)", "cell production (number of cells)"    ,  "growth anomalies"  , "dendrometer/circumference") 
2. Sapling growth: (height,  "biomass"   )
3. Putative C assimilation: ("ecosystem fluxes"  ,   "photosynthesis"  , "NDVI/greenness"    )
4. Allocation of growth: ("stem density" ,  "root:shoot ratio"   )
5. "not measured"   

Sapling growth and adult growth could also be called "radial" and "other", but since theses methods are tied to tree stage this might be an interesting insight. Or do we need a column for mature vs potted? We can probably tell from the table without having to look at the papers.

**Comment by lizzieinvancouver** [comment]
@jannekehrl @AileneKane Can we call the GPP in zohner2023 "ecosystem fluxes" or would you prefer something else? (see options above).

@rdmanzanedo What do you want growth anomalies listed as? It could go with xylogenesis or somewhere else, or we could cut the row if we think it really does not jive with the other metrics of 'growth'?

@FrederikBaumgarten Can I call the camarero2022 entry with 'annual core (simulated to intraannual)' just 'annual core'

**Comment by lizzieinvancouver** [comment]
> Are we sure stem density was a growth metric?
> 
> For growth metric how about:

@alanaroseo Thanks! I like it. Though stem density was for a shrub and they seemed to use it to guess at biomass, so for now I just have 'biomass height stems' as a category and we have only ONE entry for 'Allocation of growth' which I thin says something about how well studied that is. 

I ended up with two columns in the end depending on what folks want: 

```
> unique(sort(d$growth))
[1] "annual core"                    "biomass height stems"           "dendrometer/circumference"     
[4] "ecosystem fluxes"               "intra-annual core (xylogeneis)" "NDVI/greenness"                
[7] "not measured"                   "photosynthesis"                 "root:shoot ratio" 
```
Or ...

```
> unique(sort(d$growthsimple))
[1] "biomass height stems"    "not measured"            "putative C assimilation" "radial growth"          
[5] "root:shoot ratio"       
```

**Comment by alanaroseo** [comment]
Since these methods are very specific to juveniles or adults, with the exception of dendrometers and xylogenesis. We should consider how to separate methods from growth stage

@lizzieinvancouver  - I kinda like both versions of this column, I think they are useful for thinking about broad categories vs specific approaches., and maybe a nice way to split in the writing

**Comment by lizzieinvancouver** [comment]
> I kinda like both versions of this column, I think they are useful for thinking about broad categories vs specific approaches., and maybe a nice way to split in the writing

@alanaroseo  I agree. I found the simple one really handy when you wanted to look at growth x gsl, but the bigger one more useful otherwise. Let's keep both.

Also, just FYI -- I thought about it yesterday and my plan is that -- once we have most of the cleaning code running -- I will source it all in one file and separate out any code looking at results.

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thanks for your help on this!

**Comment by cchambe12** [comment]
@lizzieinvancouver - looks good to me! I think we have 38 papers instead of 37 because Soolananayakanahally is listed twice, once for 2013 and once for 2014? But maybe that is intentional... They have different entries for growth metrics. I've added a handful of misc comments throughout labeled with "CJC 4Aug".

**Comment by lizzieinvancouver** [comment]
@cchambe12 Thanks! I don't think Soolananayakanahally should be twice ... can you check with @alanaroseo  and update the code to fix this if so?

**Comment by jannekehrl** [comment]
@lizzieinvancouver I'd be happy with ecosystem fluxes for GPP (I think that fits with what Richardson did, and they used all or a subset of the same data).

**Comment by cchambe12** [comment]
I've fixed the issue with Soolananayakanahally and checked to make sure that GPP falls under ecosystem fluxes. This should all be set!

**Comment by cchambe12** [comment]
@lizzieinvancouver Let me know if you'd like me to take a stab at analysis and/or figures here

**Comment by lizzieinvancouver** [comment]
Very done, thanks all!
