### ISSUE TITLE
feedback on very rough first draft

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#25]
Draft [here](https://github.com/lizzieinvancouver/grephon/blob/main/docs/workingdraft.pdf). Read it quickly, and bring to the meeting or park your thoughts here.

**Comment by cchambe12** [comment]
I wish all manuscripts referenced bouncy houses and Batman!! I had a lot of fun reading this (I laughed out loud several times) and was excited to see all of our thoughts start to come together - thanks Lizzie! 

Overall, I really enjoyed how you stressed the importance of synergy across fields. I agree, this was my biggest takeaway from this group over the past year. 

**Below, I've jotted down some meandering notes:**
One thing that I would love to see as the paper evolves, is reference to more numbers from our lit review. For example, "XX studies looked at temperature x precipitation but 0 studies also looked at VPD" - or something like that. Or "only XX studies looked at biotic external factors".  Or maybe we could make a table/figure with a breakdown that can be referenced throughout the text. 

Just to confirm (for me only) - when we're talking about temperature, we're always talking about growing season temperature correct? My phenology brain can't help but always wonder if we're talking about bud development time (e.g., chilling or forcing temps). I do feel curious about how CC is impacting bud development and, thus, growth but I think that's outside the scope of this paper. 

For the _External _Drivers_  and the _Internal Programming_ sections, there are so many drivers and potential mechanisms to look at. It's a lot for the reader to digest at once since almost every paragraph is a new field of study. I like how you start saying we need Batman and Robin to bring it all together, but I'm wondering if we could warn the reader in advance by listing all the potential drivers we will discuss and then break them down as you do. I'll keep thinking about this too. Maybe another conceptual figure could help with this too. 

I think this is a very critical paper to write but also a very tricky one. It's a lot of ground to cover and we need to not overwhelm the reader. Overall, I think figures and numbers will help. I also think there is a lot of criticism throughout - which is correct - but feels a little depressing at times. I'm wondering how we can make this extremely hard question feel more attainable.

**Comment by lizzieinvancouver** [comment]
Lizzie takes notes from the **8 September 2023** meeting:

@AileneKane Some dendro issues: small phrasing tweaks that she could address. Increase emphasis on how hard it is to test these hypotheses with current dendro practices.

@kavs-P Big fan of section headings, we need more for the subfields. Figure of the subfields feeding into other subfields to support the text and she would be happy to take a stab at this.

@jannekehrl Internal programming and bat-mobile section need more structure -- the current paragraphs there could be shuffled around which is not great, so we need more order. Maybe we need an overview to organize the internal with an overview of what internal programming can be. How about making the future sections about (1) things all fields can do, (2) places groups places could move together (PEP and ITRB etc.) and multiple future places. 

@rdmanzanedo Hopeful studies and collaborations, one big wishful thinking study would be good. Good tone, but need info way sooner in intro of what direction the paper is going -- perspective, review. Rubén likes perspective with a lot of data in the background. @AileneKane and @cchambe12 also vote for perspective.

@cchambe12 Wanted more numbers for when we say things. For end, maybe table in the supp with field, what's missing, dream study, how can they connect (this could help address Janneke's point that there may be no one grand study but lots of ways to connect them). 

@FrederikBaumgarten Need more sub-headings. Need some definitions, for example what is biological time. Would like to see list of all hypotheses. 

@kavs-P Added: Yeah I was also going back and forth on what biological time means. It could like it’s age-related, but I thought it meant phenology. Maybe we need a glossary? Especially since we’re talking about different sub fields

Any overall structural problems? Need to fix the bat mobile section; needs section headers or such within it and organization.

Is the paper too overwhelming and hopeless @lizzieinvancouver asks? Fixing batmobile section could help. Maybe we also need a box of easy opportunities, like coring common gardens. Are there ways we can frame work that is what we want that is already happening? 

So far the paper does not have our opinion. What will happen in next couple of decade? @lizzieinvancouver I have a spare paragraph that did not fit in, about how you will find this in acquisitive species, and we don't know for conservative species  and you'd need different dendro methods @jannekehrl And you will see it where mainly the big change is growing season  length, but not changes in drought or other shifts. @rdmanzanedo But do we really know?

@AileneKane Noting that in the abstract we say: "A suite of diverse hypotheses, from increased drought and high temperatures, to internal limits on plant growth each year, have generally failed to coalesce around a predictive model of why longer growing seasons do, or do not, increase tree growth." The hypotheses table mentioned would be a great way to support this.

@lizzieinvancouver Add that we did a lit review to abstract maybe?

@AileneKane Should we make a bigger point of not finding terms mattered to finding the growth x GSL pattern .... see heatmap below. 

**Figures:**
- Bar graphs of studies that fell into each field @cchambe12 @lizzieinvancouver 
- Figure of the results from GREPHON team? Maybe Cat and Rubén and Alana could work on this? Heatmap of results based on growth measurements types x GSL types @cchambe12 will work on this. 
- @AileneKane Fix up the growth x elevation figure. 

**Who can work on?**
- Measurement box @AileneKane 
- Figure: PEP725 x ITRB (and maybe USA NPN) -- species/space/time @lizzieinvancouver @rdmanzanedo @cchambe12 
- @kavs-P Subfields figure
- Working on the numbers for the studies 
- List of all hypotheses (team?): @FrederikBaumgarten @AileneKane @kavs-P -- @FrederikBaumgarten will schedule meeting ASAP/make it happen ... they will consult with @alanaroseo 
- Fixing bat mobile @jannekehrl

**Comment by AileneKane** [comment]
A comment on this was made (by @FrederikBaumgarten  I think?) in our meeting and i agree- some more definitions would be helpful. For example, on page 3, it would be helpful to distinguish clearly what we mean by external vs internal drivers.

**Comment by AileneKane** [comment]
Also on page 3, the sentence that says "Further, we found little support for reports of a disconnect between growth and growing season length." This feels like a big result but is currently buried in the middle of a paragraph. Let's make more of this finding, if we can really say this with our table!

**Comment by lizzieinvancouver** [comment]
@AileneKane Good point! I am happy to have a glossary (table or box); perhaps your hypothesis team could work on that. I can define biological time then ... or we can cut that term.

**Comment by lizzieinvancouver** [comment]
Thanks for everyone's feedback! Here's the tasks due:

Figures: 
- Ruben on PEP/ITRB with Cat's and my help
- Subfields relating -- Kavya
- GREPHON table stuff, including heat map -- Cat and Lizzie
- New version of growth x elevation -- Ailene

Other
- Measurement box -- Ailene
- Fix the bat mobile section -- Janneke
- List of all hypotheses and glossary: Frederik, Ailene, Kavya with Frederik in charge of scheduling/organizing this team 

DEADLINE for all tasks: 22 September!

I will leave this issue open until I have time to work on the excellent feedback here.

**Comment by FrederikBaumgarten** [comment]
In the biotic external factors section (I would term it biotic interactions) we could say that an extended growing seasons allows for additional generation cycles in a lot of insect species that can cause massive outbreaks. Famous example is the bark beetle that is predicted to impact many forests in Europe and North America.
for example:
https://www.journals.uchicago.edu/doi/full/10.1086/665007
https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=42782508f3e7a909391dcad591fe84006c3fbf1e

**Comment by lizzieinvancouver** [comment]
I have done my best to integrate most/all comments in new draft ... I am not sure it's as exciting and cool as it should be, and the table still feels weakly integrated, but I think we're definitely heading in the right direction.
