### ISSUE TITLE
do we need to discuss CO2 fertilization?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#33]
And, if so, what's the quickest way I can do it and move on?

**Comment by lizzieinvancouver** [comment]
Side note ... Jonathan (Davies) was reading a UN document that mentioned increased carbon stored due to longer seasons, which cites [this document](https://essd.copernicus.org/articles/14/1917/2022/) which says:

> The terrestrial land sink (SLAND) is thought to be due to the combined effects of fertilization by rising atmospheric CO2 and N inputs on plant growth, as well as the effects of climate change such as the lengthening of the growing season in northern temperate and boreal areas. SLAND does not include land sinks directly resulting from land use and land-use change (e.g. regrowth of vegetation) as these are part of the land-use flux (ELUC), although system boundaries make it difficult to exactly attribute CO2 fluxes on land between SLAND and ELUC (Erb et al., 2013).

**Comment by FrederikBaumgarten** [comment]
Interesting reference. I think you can get the C02 fertilization effect of your choice depending on how well you manage to remove nutrient limitations. Nitrogen is only one piece of the equation. Phosporus is waiting right behind. And all the other elements that plants require to maintain the stochiometric balance of the tissue. More intriguing seem to me the reserve pool (but I guess that's already off topic). My experiments always showed full NSC recovery by the end of the GS, even in a full defoliation scenario. So reserves might be prioritized over growth so that reserves always end up plenty. Curious what @alanaroseo things here.

**Comment by alanaroseo** [comment]
I just had a very interesting convo with Matthais Suarer that may relate.
They are looking at within-ring variation in C13 to detect the effects of
brief droughts, as short as 2 weeks. BUT this only seems to work in
conifers and they think not with angios because they have more NSC reserves
(very true) and these are more readily tapped for growth (hadn't heard
this), so the carbon used for growth is too mixed to get the fine-scale
details. This may also suggest that growth in angiosperms has a more
additive relationship with temperature than in conifers because they are
less reliant on recently acquired carbon.

Curious Frederik, if you have seen full NSC recovery in angiosperms only or
conifers as well??

In redwood we see a progressive decrease in growth efficiency in multi-year
droughts:
Sillett, S.C., Antoine, M.E., Carroll, A.L., Graham, M.E., Chin, A.R. and
Van Pelt, R., 2022. Rangewide climatic sensitivities and non-timber values
of tall Sequoia sempervirens forests. *Forest Ecology and Management*, *526*,
p.120573.

**Comment by AileneKane** [comment]
I do think we should discuss CO2 fertilization. It is one of the hypotheses underlying why we see increased growth in some situations (reduced effects of drought due to CO2 fertilization). It may be enough to discuss in the context of hypothesis and C-source vs C sink limitation?

**Comment by lizzieinvancouver** [comment]
Discussion from meeting was: similar to @AileneKane comment that more CO2 means less drought effects etc.. Then @rdmanzanedo said, it's complicated and hard to know about drought effects. @alanaroseo means heat has less of an impact on growth.

**Comment by lizzieinvancouver** [comment]
See also issue #1 which has sink/source in the figure ... @alanaroseo if you have a simple definition of source and sink I could add now for the figure caption (and I will worry about the outline/paper later) -- let me know. No worries if not, I know you're busy!

**Comment by lizzieinvancouver** [comment]
I am mentioning this in a caption and calling it a day for now on CO2 fertilization in this paper.
