### ISSUE TITLE
feedback on second draft

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/grephon#36]
Less rough (than first draft, see issue #25), but still in less than beta testing I think. Draft [here](https://github.com/lizzieinvancouver/grephon/blob/main/docs/workingdraft.pdf). Read it please, and bring to the meeting or park your thoughts here (if you prefer, you can send comments on the PDF and email them to me, but please keep them broad at this point --- we're not yet at refining language or stuff).

**Comment by AileneKane** [comment]
The draft is looking great and I enjoyed reading it- thank you for all your work on it @lizzieinvancouver! 
Here are some comments:

1. Introduction- First paragraph: can we add some some example global carbon models/refs? I can do some research if these are not known by someone in the group already.
2. Introduction- third paragraph: the paragraph and topic sentence could better highlight the urgency and importance of our work- reviewing evidence for a fundamental relationship that is critical to assumptions of GCMs, carbon cycling, and impacts. This is important and exciting!
3. "Evidence that longer seasons increase plant growth, or not" opening paragraph needs some work to better set up the section clearly. 
4. External controllers- perhaps make clear that these are examples and not comprehensive from our lit review? and/or add nitrogen fertilization, photoperiod, carbon (source limitation), as I think these are also included in studies we reviewed
5. "An interdisciplinary framework"- i really like this point  "Taken together, the current landscape of research suggests we
may be testing a hypothesis for how plants shifts with climate change that we never previously understood well in fundamental biology."
6. "Standardizing measurements"- I found the number of different metrics used to be a powerful datapoint and makes the call for integration quite compelling. Perhaps we could highlight this more in the abstract and/or intro?
7. In addition to a unified framework and, perhaps more standardization of metrics, I think we should also urge for research to understand/report how different metrics relate to one another-e.g, is budburst or leafout typically correlated with greenup (NDVI)? When is/isn't it and why/why not? Quantifying/understanding similar relationships for different metrics of growth (height, dbh, ring width, etc) would also be helpful.
8. In the "extending disciplinary focus" section i think the bit on dendro needs some reworking. 
not sure i understand the space vs time distinction as its currently written ("over space (not time)"). i think dendro relies on temporal relationships in growing season length (i.e. shorter seasons= narrower ring widths) and traditional methods are generally intended to remove age/size related trends that occur over time within a tree....not spatial trends. 
9. There are places where we could (should?) add more refs- I'm happy to help with this. In addition to the GCM section i mentioned about, i think the "Extending disciplinary focus" section could also benefit from more refs/specific examples (e.g. the paragraph beginning with "All fields have lacked..." especially the section "Dendrochronology often uses frost events or insect outbreaks..")
10. In " Lags & allocation" I really like the point that "All fields would benefit from tackling the challenge of understanding the physiological and/or developmental connections between growing season length and growth"
11. "Quantify species/population/individual variation" - can we add "community/ecosystem" to this too?  and perhaps make more of a point of this in the ms? I think it would be especially useful to be able to relate individual/population/species phenology & growth metrics to community/ecosystem levels ones and be able to compare to NDVI/satellite based metrics. In other words, how can we scale smaller scale but more robust experiments to accurately reflect ecosystem level dynamics and variation?
12. I really like the point in the paragraph before "Where to go in the batmobile, now!" where you write "While multiple papers report a lack of relationship between growth and growing season length, we have no fundamental understanding of what the effect size of this relationship should be, and thus no way to know if we have good power in current
studies to detect it..."
13. conclusion:  I love the closing sentence!  I like the opening sentence and its point, too.
14. Some places we need to add definitions (acquisitive, conserve traits)
15. We need to check/rework Fig 1 - make sure it reflects the hypothesis table! and get feedback on images....also, are there ways we should use this information more in the ms? (see [https://github.com/lizzieinvancouver/grephon/issues/29](https://github.com/lizzieinvancouver/grephon/issues/29))
16. Do we need/want to adjust Fig 2?
17. Similarly, i like Fig 3- had not seen it before- and think we might be able to use/cite it more. For example, in lags and allocation section could we make a point about vegetative vs wood growth/phenology (highlighted in this fig)?

**Comment by cchambe12** [comment]
Sorry for the delay on this but the draft looks great!! I think the figures look really good and the text reads well. Overall, I like the structure of the paper and _love_ how actually useful the Batmobile section actually is. Also, glad to see the batmobile still exists! Thank you for all of your work on this @lizzieinvancouver - it's not an easy feat to include all of our "must-have" points into one, concise paper and to do it well. 

Introduction - I think reads well, there were moments that felt a bit repetitive, but I think we can clean that up fairly easily when we get into the nitty gritty details. I also agree with Ailene, that emphasizing the urgency of this question is critical! Tangentially, there's a huge push for programs to classify carbon credits as either "reductions" due to avoided emissions or "removals" from increased growth. I think this paper could be critical not only in forecasts but in tempering underlying assumptions about future growth. 

"Evidence that longer seasons increase plant growth, or not" - I like this section! I think it's cool how you're like, hey there's this very compelling hypothesis but guess what, plants aren't that easy to predict and here's why. 

"Controllers on growth × growing season length relationships" I think this opening paragraph can be set up a bit better. I found myself looking for paragraph headers with the fields listed. Or actually I think this section can be reorganized a bit. All the points are there but I think there could be a different flow. I like separating out External vs Internal and then I think population and individual limits should be separated. 

"An interdisciplinary framework for growth × growing season length relationships" - overall I thought this was a good section. I think it brings together a lot of interesting pieces we learned from the lit review and I wonder if more of this can be brought into the abstract/introduction.
"Standardized measurements" - this was great! I thought the point was very clear and a strong finding from the group.
"Bridging the internal-external drivers divide" - also good. Maybe add an example of a paper that does this well? If that exists.
 

"Conclusion" - is very refreshing! It's a new take on the problem we all read about over and over again and I think you do a great job stressing the point here is to get better at understanding our new world, which feels more attainable than fixing climate change completely.

**Comment by lizzieinvancouver** [comment]
It's a GREPHON meeting! And @lizzieinvancouver is taking notes:

@alanaroseo Good subheaders, needs some better transitions, she can add specific comments. We also need to deal with sink/source limitation. We discussed this and decided to have @alanaroseo write up some sentences about the general disagreement and we will try to fit this as part of our argument. 

@AileneKane Can help with adding some excitement and refs. She could also help adding a way to scale up to community/ecosystem (from individual/population) in the quantifying species and population stuff ... she can help write this up with @cchambe12 

@kavs-P Liked opening with the debate not settled and that we need to go back and rethink core assumptions. Moving from controllers on growth and then to next section on interdisciplinary needs more equal examples (but the examples are elsewhere); for example, bridging the external and internal divide is too short.

@jannekehrl As @kavs-P said, did not like how we wrote the Zohner solstice section, maybe we could move it around within that section.  Internal constraints could be moved around to clarify the flow. Or @cchambe12 suggested moving this to make it a concluding paragraph? 

@jannekehrl Will work on internal constraints that needs more conceptual and organizing. Need to clarify the difference between the two last major sections. Make the bat mobile section a suite of questions (and a new name for the subheader would help). 

@cchambe12 Found the second half is better than the first; and liked the next steps being longer and more actionable. Abstract needs more points from the second half to make it more exciting (and less repetitive with intro), like add `Standardized measurements' stuff. Maybe add in carbon markets stuff? @cchambe12 Can add stuff and refs that might connect to carbon markets. 

Controllers on growth and growing season length -- can we organize by the disciplines that we list at the beginning of the section?

@rdmanzanedo Make the point about not just fixing metrics, but thinking more deeply *earlier* and the figures/analyses don't feel well integrated. We could sound more positive about amount of data for dendro (and phenology?). Maybe at the end (or somewhere) we need to say that our solutions apply to other spatio-temporal problems? 

@cchambe12 Can help with integrating the data into the text!

@rdmanzanedo @AileneKane @kavs-P @FrederikBaumgarten will continue their awesome work to fix and make figure 1 (hypothesis figure) better integrated with the language in the text (and points in the text). See issue #29.

@alanaroseo and @jannekehrl will find a way to tuck in CO2 fertilization at the beginning maybe? 

Lizzie will get fixes for dendro from @AileneKane and @rdmanzanedo.

Too many subheaders?: No.

**Comment by AileneKane** [comment]
I changed some text in the Extending disciplinary focus section and added some notes to the workingdraft.RNW file (including some notes preceded by %AKE). One query: on this sentence/ref:
Fundamentally, the field has long assumed growth decreases with shorter growing seasons \citep[e.g.,][]{bruening2017} over space, such as higher elevations and latitudes.%AKE: I have not read bruening carefully but a skim of it suggests that it is not a tree ring paper- rather a treeline paper. @lizzieinvancouver do we still want to cite it here or instead look for another one that is more dendro focused?

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks for all your efforts! A paper on tree rings would be much better than Bruening if you have one.

**Comment by lizzieinvancouver** [comment]
I have done what I can -- new draft coming soon!
